name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # output the name of the event that triggered the workflow
      - run: echo ${{ github.event_name }}
      # output the name of the branch taht the repository is on
      - run: echo ${{ github.ref }}
      # list all files in the repository
      - run: echo ${{ github.repository }}
